version: "3.5"

services:
  visual-regression-tester:
    build: ./docker/node
    working_dir: /opt/visual-regression-tester-app
    user: "${RUN_UID}:${RUN_GID}"
    ports:
      - "61423:61423"
    environment:
      - HOME=/home/visual-regression-tester
    volumes:
      - ./:/opt/visual-regression-tester-app:cached
      - home:/home/visual-regression-tester
      - node-modules:/opt/visual-regression-tester-app/node_modules
  change-volume-owner:
    image: node:10.15.3-alpine@sha256:b85a3b0ef76f5543b3f467e8a25694e72594d2c2bfcf140fa584d4f40ace4130
    volumes:
      - home:/opt/visual-regression-tester-volumes/home
      - node-modules:/opt/visual-regression-tester-volumes/node_modules
    command: |
      sh -c "chown ${RUN_UID}:${RUN_GID} /opt/visual-regression-tester-volumes/*"
volumes:
  home:
  node-modules:
