on:
  push
name: 'Visual Regression Tester'
jobs:
  visual-regression-tester:
    name: 'Visual Regression Tester'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Install'
        uses: ./docker/node/
        with:
          entrypoint: run-install
      - name: 'Build'
        uses: ./docker/node/
        with:
          entrypoint: run-build
      - name: 'Test'
        uses: ./docker/node/
        with:
          entrypoint: run-test
